export default {
    ACADEMIC_REPORTS : "academic_reports",
    ACADEMIC_REPORT_ITEMS : "academic_report_items",
    ADMINS : "admins",
    AFFECTIVE : "affective",
    AUTO_NUMBERING : "auto_numbering",
    AVAILABILITIES : "availabilities",
    AVAILABILITY_TIMES : "availability_times",
    CAPABILITIES : "capabilities",
    CITIES : "cities",
    COURSE_MODE : "cource_mode",
    DAYS : "days",
    DEGREES : "degrees",
    EMERGENCY_CONTACT_RELATION : "emergency_contact_relation",
    FEES : "fees",
    FEE_COMPONENTS : "fee_components",
    FEE_ITEMS : "fee_items",
    GENDERS : "genders",
    GRADES : "grades",
    INVOICES: "invoices",
    INVOICE_COMPONENTS: "invoice_components",
    INVOICE_ITEMS: "invoice_items",
    INVOICE_STUDENTS: "invoice_students",
    MENUS : "menus",
    MODE : "mode",
    NOTIFICATIONS: "notifications",
    PRESENCE_NOTE_TYPE : "presence_note_type",
    PRESENCE_REPORT_NOTES : "presence_report_notes",
    PRESENCE_SCHEDULE_NOTES : "presence_schedule_notes",
    PROGRAMS : "programs",
    PROVINCES : "provinces",
    REPORTS : "reports",
    REPORT_CHANGE_LOGS : "report_change_logs",
    ROLE_MENU : "role_menu",
    ROLES : "roles",
    SCHEDULES : "schedules",
    STUDENT_STATUS : "student_status",
    STUDENTS : "students",
    SUBJECTS : "subjects",
    TUTOR_AVAILABILITIES : "tutor_availabilities",
    TUTOR_CAPABILITIES : "tutor_capabilities",
    TUTORS : "tutors",
    USER_EMERGENCY_CONTACT : "user_emergency_contact",
    USERS : "users"
}